# Filetype dependant
####################

## Langage

[[plugins]]
repo = 'luochen1990/rainbow'
on_ft = ['c', 'cpp', 'go', 'ruby', 'javascript']

# C / CPP

[[plugins]]
repo  = 'justmao945/vim-clang'
on_ft = ['c','cpp']
if    = "has('python')"

[[plugins]]
repo  = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c','cpp']

[[plugins]]
repo    = 'ilyachur/cmake4vim'
depends = ['vim-dispatch', 'ctrlp.vim']
on_ft   = ['c', 'cpp', 'tex']
on_cmd  = ['CMake', 'CMake!']

# Python

[[plugins]]
repo  = 'davidhalter/jedi-vim'
on_ft = 'python'

# Golang

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = 'go'

# Javascript

[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'npm install'
if    ='executable("npm")'
on_ft = ['javascript', 'json', 'css', 'scss', 'html', 'typescript']

## Modeling langage

# XML / HTML

[[plugins]]
repo  = 'sukima/xmledit'
on_ft = ['xml','html']

# Latex

[[plugins]]
repo  = 'lervag/vimtex'
on_ft = 'tex'

# Markdown

[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = 'markdown'

# TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


## Build system

[[plugins]]
repo  = 'richq/vim-cmake-completion'
on_ft = 'cmake'

[[plugins]]
repo  = 'nickhutchinson/vim-cmake-syntax'
on_ft = 'cmake'

