# [[plugins]]
# repo = 'godlygeek/csapprox'
# if = "v:progname !=# 'gvim' && has('gui') && !has('nvim')"
# hook_add = '''
# " Convert colorscheme in Konsole.
#  let g:CSApprox_konsole = 1
#  let g:CSApprox_attr_map = { 'bold' : 'bold', 'italic' : '', 'sp' : '' }
# '''

# [[plugins]]
# repo = 'thinca/vim-guicolorscheme'
# if = "v:progname !=# 'gvim' && !has('gui') && !has('nvim')"

[[plugins]]
repo = 'Shougo/dein.vim'

# Default list of plugins
#########################

# GUI

[[plugins]]
repo   = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeFind', 'NERDTreeToggle']

[[plugins]]
repo   = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo   = 'mbbill/undotree'
on_cmd = 'UndotreeToggle'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'myusuf3/numbers.vim'

[[plugins]]
repo = 'junegunn/vim-peekaboo'

[[plugins]]
repo = 'CharlesGueunet/quickmenu.vim'

[[plugins]]
repo = 'tpope/vim-dispatch'

# Versionning

[[plugins]]
repo = 'airblade/vim-gitgutter'

# Operator /  Selection / Region

[[plugins]]
repo = 'Raimondi/delimitMate'
on_i = 1

[[plugins]]
repo = 'kana/vim-textobj-user'
on_i = 1

[[plugins]]
repo    = 'sgur/vim-textobj-parameter'
depends = 'vim-textobj-user'
on_i    = 1

[[plugins]]
repo    = 'glts/vim-textobj-comment'
depends = 'vim-textobj-user'
on_i    = 1

[[plugins]]
repo    = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
on_i    = 1

[[plugins]]
repo    = 'rhysd/vim-textobj-anyblock'
depends = 'vim-textobj-user'
on_i    = 1

[[plugins]]
repo    = 'kana/vim-textobj-entire'
depends = 'vim-textobj-user'
on_i    = 1

[[plugins]]
repo = 'tpope/vim-commentary'
on_i = 1

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'tpope/vim-surround'

# Buffers / Tabs / motions

[[plugins]]
repo   = 'ctrlpvim/ctrlp.vim'
on_cmd = ['CtrlP', 'CtrlPBuffer', 'CtrlPMixed', 'CtrlPLine', 'CtrlPBufTag', 'CtrlPQuickfix']

[[plugins]]
repo   = 'corntrace/bufexplorer'
on_cmd = ['BufExplorer', 'BufExplorerVerticalSplit', 'BufExplorerHorizontalSplit']

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

# Search & Replace

[[plugins]]
repo   = 'markonm/traces.vim'
# on_cmd = 's'

[[plugins]]
repo   = 'brooth/far.vim'
on_cmd = ['F', 'Far', 'Farp']

# Text process

[[plugins]]
repo = 'tommcdo/vim-lion'

[[plugins]]
repo   = 'AndrewRadev/switch.vim'
on_cmd = ['Switch', 'SwitchReverse']

[[plugins]]
repo = 'joereynolds/place.vim'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

# Completion / Snippets / Utility

[[plugins]]
repo = 'lifepillar/vim-mucomplete'
on_i = 1

[[plugins]]
repo = 'CharlesGueunet/VimFilify'

[[plugins]]
repo    = 'w0rp/ale'
depends = 'VimFilify'

[[plugins]]
repo = 'garbas/vim-snipmate'
depends = ['vim-addon-mw-utils', 'tlib_vim']

[[plugins]]
repo = 'GuillaumeFavelier/vim-snipmate-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-repeat'

# Lib & Tools for plugins

[[plugins]]
repo = 'tomtom/tlib_vim'

[[plugins]]
repo = 'MarcWeber/vim-addon-mw-utils'


