# Filetype dependant
####################

## Langage

# Build system

[[plugins]]
repo    = 'ilyachur/cmake4vim'
depends = ['vim-dispatch', 'ctrlp.vim']
on_ft   = ['c', 'cpp', 'tex']
on_cmd  = ['CMake', 'CMake!']

# C / CPP

[[plugins]]
repo  = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c','cpp']

# Python

[[plugins]]
repo = 'neoclide/coc-python'
depends = 'coc.nvim'
on_ft = 'python'

# Golang

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = 'go'

# Javascript

[[plugins]]
repo  = 'prettier/vim-prettier'
build = 'npm install'
if    ='executable("npm")'
on_ft = ['javascript', 'json', 'css', 'scss', 'html', 'typescript']

# [[plugins]] # install with :CoCInstall coc-tsserver
# repo = 'neoclide/coc-tsserver'
# depends = 'coc.nvim'
# on_ft = ['javascript','typescript']

## Modeling langage

# XML / HTML

[[plugins]]
repo  = 'sukima/xmledit'
on_ft = ['xml','html']

# Latex

[[plugins]]
repo  = 'lervag/vimtex'
on_ft = 'tex'

[[plugins]]
repo = 'neoclide/coc-vimtex'
on_ft = 'tex'
depends = ['coc.nvim', 'vimtex']

# Markdown

[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = 'markdown'

# TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


## Build system

[[plugins]]
repo  = 'richq/vim-cmake-completion'
on_ft = 'cmake'

[[plugins]]
repo  = 'nickhutchinson/vim-cmake-syntax'
on_ft = 'cmake'

